import Leftbar from '@/components/Leftbar'
import Navbar from '@/components/Navbar'
import Posts from '@/components/Posts'
import Profile from '@/components/Profile'
import Rightbar from '@/components/Rightbar'
import axios from 'axios'
import Head from 'next/head'
import { useEffect, useLayoutEffect, useState } from 'react'
import Login from './login'
import jwt from 'jsonwebtoken';

export async function getServerSideProps(context) {

  try {
    const res = await axios.get(`${process.env.NEXT_PUBLIC_URL}/api/post`);
    // console.log(res.data)

    const token = context.req.cookies.jwt;
    const payload = jwt.verify(token, process.env.JWT_KEY);

    if (!payload.user_id) throw new Error("Invalid")

    return {
      props: {
        postData: res?.data || [],
        isAuth: true,
      }
    }
  } catch (error) {
    console.log(error);
    return {
      props: {
        postData: [],
        isAuth: false
      }
    }
  }
}

export default function Home({ postData, isAuth }) {

  const [user, setUser] = useState(isAuth);

  const [modal, setModal] = useState(false);

  useEffect(() => {
    setUser(JSON.parse(localStorage.getItem('user')));
  }, []);

  return (
    <>
      <Head>
        <title>Social App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user ?
        <div>
          <Navbar />

          <div className='flex'>

            <div className='flex-[0] lg:flex-[2]'>
              <Leftbar setModal={setModal} />
            </div>

            <div className='flex-[12] lg:flex-[6]'>
              {
                modal
                  ? <Profile />
                  : <Posts postData={postData} />
              }
            </div>

            <div className='flex-[0] lg:flex-[4]'>
              <Rightbar />
            </div>

          </div>

        </div>
        :
        <Login />
      }

    </>
  )
}
